---
- hosts: ansible
  vars:
    http_port: 80
    max_clients: 100
  remote_user: vagrant
  become: yes
  become_method: sudo
  tasks:
  - name: ensure apache is at the latest version
    apt: pkg=apache2 state=present
  # - name: write the apache config file
  #   template: src=/srv/httpd.j2 dest=/etc/httpd.conf
  #   notify:
  #   - restart apache
  - name: ensure apache is running (and enable it at boot)
    service: name=apache2 state=started enabled=yes
  handlers:
    - name: restart apache
      service: name=httpd state=restarted
