---

# name: Install packages for docker
# become: yes
# become_method: sudo
# apt: name={{item}} state=installed
# with_items:
#   - apt-transport-https
#   - ca-certificates

# sudo apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D

#- name: add docker apt key
#  become: yes
#  become_method: sudo
#  apt_key:
#    url: hkp://p80.pool.sks-keyservers.net:80
#    id: 36A1D7869245C8950F966E92D8576A8BA88D21E9
#    state: present

- stat: path=/usr/bin/docker
  register: p

# - name: instal docker
#   shell: "curl -fsSL https://get.docker.com/ | sh"
#   when: p.stat.exists == False

# python 2.7.9~ is needed below
# - name: download docker install script
#   get_url: url=https://get.docker.com/ dest=~/docker.sh mode=0755
#   when: p.stat.exists == False
#
# - name: install docker
#   become: yes
#   become_method: sudo
#   command: "sh ~/docker.sh"
#   when: p.stat.exists == False
#
# - name: remove docker install script
#   file: path=~/docker.sh state=absent
#   when: p.stat.exists == False

- command: docker -v
  register: msg
- debug: var=msg

