---
- name: Install Requirement for git
  become: yes
  become_method: sudo
  apt: name={{item}} state=installed
  with_items:
    - libcurl4-gnutls-dev
    - libexpat1-dev
    - gettext
    - libz-dev
    - libssl-dev
    - python-software-properties

- name: register git repository
  apt_repository: repo='ppa:git-core/ppa'
  become: yes
  become_method: sudo

- name: update apt
  apt: update_cache=yes
  become: yes
  become_method: sudo

- name: Install git
  apt: name=git state=present
  become: yes
  become_method: sudo

- name: Set .gitconfig file
  template: src=gitconfig.j2 dest=~/.gitconfig

