---
- name: Install Requirement for git
  become: yes
  become_method: sudo
  apt: name={{item}} state=installed
  with_items:
    - libcurl4-gnutls-dev
    - libexpat1-dev
    - gettext
    - libz-dev
    - libssl-dev
    - python-software-properties
    - exuberant-ctags

- name: register git repository
  apt_repository: repo='ppa:git-core/ppa'
  become: yes
  become_method: sudo

- name: update apt
  apt: update_cache=yes
  become: yes
  become_method: sudo

- name: Install git
  apt: name=git state=present
  become: yes
  become_method: sudo

# github.com doesn't recognize
# - name: copy local gpg keys
#   copy: src=~/.gnupg dest=/home/{{ user }}/ mode=600
#
# - name: change .gnupg directory permission
#   become: yes
#   become_method: sudo
#   file:
#     path: "/home/{{ user }}/.gnupg"
#     owner: "{{ user }}"
#     group: "{{ user }}"
#     mode: 0700

- name: Set .gitconfig file
  template: src=gitconfig.j2 dest=~/.gitconfig force=no

