---
- name: change apt source list
  become: yes
  become_method: sudo
  shell: sed -i".bak" 's/http:\/\/archive.ubuntu.com\/ubuntu/http:\/\/ftp.jaist.ac.jp\/pub\/Linux\/ubuntu/' /etc/apt/sources.list

- name: update apt
  apt: update_cache=yes
  become: yes
  become_method: sudo

- name: Configure bash file
  template: src=bashrc.j2 dest=~/.bashrc
  tags: bashrc

- name: Install packages for dev
  become: yes
  become_method: sudo
  apt: name={{item}} state=installed
  with_items:
    - tree
    - tig
    - sysv-rc-conf
    - language-pack-ja-base

- name: Install git
  include: git.yml
  tags: git

- name: install vim
  include: vim.yml
  tags: vim

- name: install php
  include: php.yml
  tags: php

