---
- name: register php repository
  apt_repository: repo='ppa:ondrej/php5-5.6'
  become: yes
  become_method: sudo

- name: update apt
  apt: update_cache=yes
  become: yes
  become_method: sudo

- name: Install Requirement
  become: yes
  become_method: sudo
  apt: name={{item}} state=installed
  with_items:
    - python-software-properties

- name: Install php
  become: yes
  become_method: sudo
  apt: name={{item}} state=installed
  with_items:
    - php5
    - php5-cli
    - curl
    - libcurl3
    - libcurl3-dev
    - php5-curl
    - php5-gd
    - php5-mysql
    - php5-mcrypt

- name: change apache2/php.ini
  become: yes
  become_method: sudo
  template: src=php.ini.j2 dest=/etc/php5/apache2/php.ini
  notify: restart apache

- name: change cli/php.ini
  become: yes
  become_method: sudo
  template: src=php-cli.ini.j2 dest=/etc/php5/cli/php.ini
  notify: restart apache


- stat: path=/usr/local/bin/composer
  register: p

- name: download composer install script
  get_url: url=https://getcomposer.org/installer dest=~/composer.php mode=0755
  when: p.stat.exists == False

- name: install composer
  command: "php -f ~/composer.php"
  when: p.stat.exists == False

- name: set composer
  become: yes
  become_method: sudo
  command: "mv /home/{{ ansible_ssh_user }}/composer.phar /usr/local/bin/composer"
  when: p.stat.exists == False

- name: remove NeoBundle setup script
  file: path=~/composer.php state=absent
  when: p.stat.exists == False

- command: composer -v
  register: msg
- debug: var=msg

- name: set composer path to PATH
  lineinfile:
    dest: ~/.bashrc
    state: present
    regexp: "export PATH=$HOME/.composer/vendor/bin:$PATH"
    line: "export PATH=$HOME/.composer/vendor/bin:$PATH"

## phpunit skelgen
#composer global require 'phpunit/phpunit-skeleton-generator=*'

# phpcs
#composer global require 'squizlabs/php_codesniffer:*'
#phpcs --standard=PSR1,PSR2

# xdebug
#sudo apt-get install pear
#pear version

#sudo apt-get install php5-dev
#sudo pecl install xdebug

#vi /etc/php5/apache2/php.ini
#zend_extension=/usr/lib/php5/20121212/xdebug.so
## xdebug.profiler_enable=1
#xdebug.profiler_enable_trigger=1

#sudo apt-get install kcachegrind

