---
- name: Install ntp
  become: yes
  become_method: sudo
  apt: name=ntp state=present
  tags: ntp

- name: Configure ntp file
  become: yes
  become_method: sudo
  template: src=ntp.conf.j2 dest=/etc/ntp.conf
  tags: ntp
  notify: restart ntp

- name: Start the ntp service
  become: yes
  become_method: sudo
  service: name=ntp state=started enabled=yes
  tags: ntp

- name: set first dns server
  when: user != 'vagrant'
  become: yes
  become_method: sudo
  lineinfile:
    dest: /etc/network/interfaces
    create: yes
    state: present
    regexp: ^dns-nameservers {{item}}
    line: dns-nameservers {{item}}
  with_items:
    - "{{dns1st}}"
    - "{{dns2nd}}"
  notify: restart network

# does't work, stop connecting through ssh
# - name: Setup ufw
#   become: yes
#   become_method: sudo
#   ufw: state=enabled policy=deny
#   tags: firewall

- name: Allow ssh traffic
  become: yes
  become_method: sudo
  ufw: rule=allow port={{ item }} proto=tcp
  with_items:
  - "{{ ssh_port }}"
  - 80
  - 443
  tags: firewall
# - name: Set firewall default policy
#   become: yes
#   become_method: sudo
#   ufw: state=enabled policy=reject
#
# - name: Set firewall allow
#   become: yes
#   become_method: sudo
#   ufw: rule=allow port={{ item }}
#   with_items:
#   - "{{ ssh_port }}"
#   - 80
#   - 443

- name: Allow mosh
  become: yes
  become_method: sudo
  ufw: rule=allow app=mosh
