---
- name: Install ntp
  apt: name=ntp state=present
  tags: ntp
  become: yes
  become_method: sudo

- name: Configure ntp file
  template: src=ntp.conf.j2 dest=/etc/ntp.conf
  tags: ntp
  become: yes
  become_method: sudo
  notify: restart ntp

- name: Start the ntp service
  service: name=ntp state=started enabled=yes
  tags: ntp
  become: yes
  become_method: sudo

- name: set first dns server
  become: yes
  become_method: sudo
  lineinfile:
    dest: /etc/network/interfaces
    create: yes
    state: present
    regexp: ^dns-nameservers {{item}}
    line: dns-nameservers {{item}}
  with_items:
    - "{{dns1st}}"
    - "{{dns2nd}}"
  notify: restart network

