---
# - hosts: ansible
#   roles:
#   - { role: dresden-weekly.Rails }

- name: prepare development environment
  hosts: ansible
  remote_user: "{{user}}"
  roles:
    - dev

- name: apply common configuration
  hosts: ansible
  remote_user: "{{user}}"
  roles:
    - common

- name: configure and deploy the webservers and application code
  hosts: ansible
  remote_user: "{{user}}"

  roles:
    - web

- name: deploy MySQL and configure the databases
  hosts: ansible
  remote_user: "{{user}}"

  roles:
    - db

# - name: install ruby
#   hosts: ansible
#   remote_user: "{{user}}"
#
#   roles:
#     - ruby
