---
# ansible-galaxy install geerlingguy.composer
# ansible-galaxy install zzet.rbenv

- name: prepare development environment
  hosts: dev
  remote_user: "{{user}}"
  tags: dev
  roles:
    - dev

# https://galaxy.ansible.com/geerlingguy/composer/
- name: install composer
  hosts: dev
  become: yes
  become_method: sudo
  tags: php
  vars:
    composer_home_owner: "{{user}}"
    composer_home_group: "{{user}}"
    composer_global_packages:
      - { name: phpunit/phpunit }
  roles:
    - geerlingguy.composer

- name: apply common configuration
  hosts: common
  remote_user: "{{user}}"
  tags: common
  roles:
    - common

- name: deploy the webservers
  hosts: web
  remote_user: "{{user}}"
  tags: web
  roles:
    - web

- name: deploy MySQL and configure the databases
  hosts: db
  remote_user: "{{user}}"
  tags: db
  roles:
    - db

# https://galaxy.ansible.com/detail#/role/102
- name: install ruby and rbenv
  hosts: ruby
  become: yes
  become_method: sudo
  gather_facts: true # https://github.com/zzet/ansible-rbenv-role/issues/37
  vars:
    rbenv:
      env: system
      version: v1.0.0
      ruby_version: 2.3.0
  roles:
    - role: zzet.rbenv
      rbenv_users:
        - user

- name: install gem
  hosts: ruby
  remote_user: "{{user}}"
  tags: gem
  roles:
    - ruby

- name: install wp-cli
  hosts: ansible
  remote_user: "{{user}}"
  tags: wp
  roles:
    - wordpress

- name: install nginx
  hosts: nginx
  remote_user: "{{user}}"
  tags: nginx
  roles:
    - nginx

# - name: install ruby
#   hosts: ansible
#   remote_user: "{{user}}"
#   vars:
#     ruby_version: 2.2.4
#   tags: ruby
#   roles:
#     - ruby
