---
- name: Create Application Database
  become: yes
  become_method: sudo
  mysql_db: name={{ dbname }} state=present

- name: Create Application DB User
  become: yes
  become_method: sudo
  mysql_user: name={{ dbuser }} password={{ dbpassword }} priv=*.*:ALL host='localhost' state=present
