---
- name: Install Mysql package
  become: yes
  become_method: sudo
  apt: name={{item}} state=installed
  with_items:
    - mysql-server
    - python-mysqldb
    - build-essential
    - python-dev
    - libmysqlclient-dev

- name: Create Mysql configuration file
  become: yes
  become_method: sudo
  template: src=my.cnf.j2 dest=/etc/my.cnf
  notify:
  - restart mysql

- name: Start Mysql Service
  become: yes
  become_method: sudo
  service: name=mysql state=started enabled=yes

- name: Create Application Database
  become: yes
  become_method: sudo
  mysql_db: name={{ dbname }} state=present

- name: Create Application DB User
  become: yes
  become_method: sudo
  mysql_user: name={{ dbuser }} password={{ upassword }} priv=*.*:ALL host='%' state=present
