---
- name: Install Mysql package
  become: yes
  become_method: sudo
  apt: name={{item}} state=installed
  with_items:
    - mysql-server
    - python-mysqldb
    - build-essential
    - python-dev
    - libmysqlclient-dev
  #
  # mysql_user: name=root host={{item}} password={{db_root_password}}
  # with_items:
  #   - 127.0.0.1
  #   - localhost

- name: set root password
  become: yes
  become_method: sudo
  template: src=root.my.cnf.j2 dest=/root/.my.cnf owner=root mode=0600

- name: Create Mysql configuration file
  become: yes
  become_method: sudo
  template: src=my.cnf.j2 dest=/etc/mysql/my.cnf
  notify:
  - restart mysql

- name: Start Mysql Service
  become: yes
  become_method: sudo
  service: name=mysql state=started enabled=yes

# - name: Create Application Database
#   become: yes
#   become_method: sudo
#   mysql_db: name={{ dbname }} state=present

- name: Create Application DB User
  become: yes
  become_method: sudo
  mysql_user: name={{ dbuser }} password={{ upassword }} priv=*.*:ALL host='%' state=present
