---
- name: Install wp-cli
  become: yes
  become_method: sudo
  get_url:
    url: "{{ wp_cli_phar_url }}"
    dest: "{{ wp_cli_bin_path }}"
    mode: 0755

- name: Install wp-cli tab completions
  become: yes
  become_method: sudo
  get_url:
    url: "{{ wp_cli_completion_url }}"
    dest: "{{ wp_cli_completion_path }}"
    mode: 0644

